# Generated by Django 4.2.2 on 2023-07-13 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_remove_usuario_futuras_compras_futurascompra_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='futurascompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='futurascompras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ContasFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('relatoriodecontafixas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contasfixas', to='conta.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contasfixas_usuarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
