# Generated by Django 4.2.2 on 2023-07-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_conta_usuario_alter_futurascompra_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recebimento',
            name='descricao_extra',
        ),
        migrations.RemoveField(
            model_name='recebimento',
            name='valor_extra',
        ),
        migrations.AlterField(
            model_name='futurascompra',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
