# Generated by Django 4.2.2 on 2023-07-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_remove_recebimento_descricao_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurascompra',
            name='url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
