# Generated by Django 4.2.2 on 2023-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_alter_futurascompra_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurascompra',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
