# Generated by Django 4.2.2 on 2023-07-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0007_alter_futurascompra_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContasFixa',
        ),
    ]
