# Generated by Django 4.2.2 on 2023-07-24 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0009_contasavencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasavencer',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contasavencer', to=settings.AUTH_USER_MODEL),
        ),
    ]
