# Generated by Django 4.2.2 on 2023-07-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0010_alter_contasavencer_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default="+55 (35) 1234-5678", max_length=30),
            preserve_default=False,
        ),
    ]
