# Generated by Django 4.2.2 on 2023-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0011_remove_usuario_data_criacao_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='+55 (11) 1234-5678', max_length=30),
        ),
    ]
